/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mscompapp;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.Timer;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());
    
    /**
     * Creates new form Dashboard
     */
    public Dashboard(String username) {
        initComponents();
        Login.namaUser = username;
        lblWelcome.setText("Selamat Datang, " + username);
        panelutama();
        
        Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
                // Format tanggal dan waktu
                SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMMM yyyy HH:mm:ss");
                String waktuSekarang = sdf.format(new Date());
                lblTanggal.setText(waktuSekarang);
            }
        });
        timer.start();
    }
    
    private void switchPanel(javax.swing.JPanel panel) {
        pMain.removeAll();        // Menghapus panel lama yang ada di pMain
        pMain.add(panel);         // Menambahkan panel baru (PKelUser)
        pMain.repaint();          // Menggambar ulang tampilan
        pMain.revalidate();       // Menyusun ulang layout agar pas
    }
    
    private void panelutama() {
        pMain.removeAll();        // Menghapus panel lama yang ada di pMain
        pMain.add(new beranda());         // Menambahkan panel baru (PKelUser)
        pMain.repaint();          // Menggambar ulang tampilan
        pMain.revalidate();       // Menyusun ulang layout agar pas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNav = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pSide = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblKelolaUser = new javax.swing.JLabel();
        lblKelolaBarang = new javax.swing.JLabel();
        btLogout = new javax.swing.JButton();
        lblKelolaKategori = new javax.swing.JLabel();
        lblKelStock = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pNav.setBackground(new java.awt.Color(102, 102, 255));
        pNav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblWelcome.setText("Welcome");
        pNav.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 20, -1, -1));

        lblTanggal.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        lblTanggal.setText("Tanggal");
        pNav.add(lblTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo toko.png"))); // NOI18N
        pNav.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 421, 100));

        getContentPane().add(pNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 120));

        pSide.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        jLabel1.setText("Menu");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        lblKelolaUser.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        lblKelolaUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        lblKelolaUser.setText("Kelola User");
        lblKelolaUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKelolaUserMouseClicked(evt);
            }
        });

        lblKelolaBarang.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        lblKelolaBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list.png"))); // NOI18N
        lblKelolaBarang.setText("Kelola Barang");
        lblKelolaBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKelolaBarangMouseClicked(evt);
            }
        });

        btLogout.setBackground(new java.awt.Color(255, 51, 51));
        btLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btLogout.setText("LOGOUT");
        btLogout.addActionListener(this::btLogoutActionPerformed);

        lblKelolaKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblKelolaKategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kategori.png"))); // NOI18N
        lblKelolaKategori.setText("Kategori");
        lblKelolaKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKelolaKategoriMouseClicked(evt);
            }
        });

        lblKelStock.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        lblKelStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/process.png"))); // NOI18N
        lblKelStock.setText("Kelola Stock");
        lblKelStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKelStockMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wrench.png"))); // NOI18N
        jLabel3.setText("Kelola Service");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pSideLayout = new javax.swing.GroupLayout(pSide);
        pSide.setLayout(pSideLayout);
        pSideLayout.setHorizontalGroup(
            pSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSideLayout.createSequentialGroup()
                .addGroup(pSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSideLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btLogout))
                    .addGroup(pSideLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKelolaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKelolaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKelStock)
                            .addComponent(jLabel3)
                            .addComponent(lblKelolaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pSideLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        pSideLayout.setVerticalGroup(
            pSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSideLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(lblKelolaUser)
                .addGap(18, 18, 18)
                .addComponent(lblKelolaBarang)
                .addGap(18, 18, 18)
                .addComponent(lblKelolaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblKelStock)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(559, 559, 559)
                .addComponent(btLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, 980));

        pMain.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 1720, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblKelolaUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKelolaUserMouseClicked
        // TODO add your handling code here:
        switchPanel(new PKelUser());
    }//GEN-LAST:event_lblKelolaUserMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        switchPanel(new beranda());
    }//GEN-LAST:event_jLabel1MouseClicked

    private void lblKelolaBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKelolaBarangMouseClicked
        // TODO add your handling code here:
        switchPanel(new PKelBarang());

    }//GEN-LAST:event_lblKelolaBarangMouseClicked

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // TODO add your handling code here:
        int jawaban = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin Logout?", 
                "Konfirmasi Keluar", 
                JOptionPane.YES_NO_OPTION);
        
        if (jawaban == JOptionPane.YES_OPTION) {
            // 2. Tutup Dashboard saat ini
            this.dispose();
            
            // 3. Buka kembali halaman Login
            Login loginPage = new Login();
            loginPage.setVisible(true);
            loginPage.setLocationRelativeTo(null); // Biar muncul di tengah layar
        }

    }//GEN-LAST:event_btLogoutActionPerformed

    private void lblKelolaKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKelolaKategoriMouseClicked
        // TODO add your handling code here:
        switchPanel(new PKelKategori());
    }//GEN-LAST:event_lblKelolaKategoriMouseClicked

    private void lblKelStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKelStockMouseClicked
        // TODO add your handling code here:
                switchPanel(new PKelStok());

    }//GEN-LAST:event_lblKelStockMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
                        switchPanel(new PKelService());

    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblKelStock;
    private javax.swing.JLabel lblKelolaBarang;
    private javax.swing.JLabel lblKelolaKategori;
    private javax.swing.JLabel lblKelolaUser;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pNav;
    private javax.swing.JPanel pSide;
    // End of variables declaration//GEN-END:variables
}
