/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mscompapp;
import java.sql.*;
import config.Koneksi;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class DetailService extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetailService.class.getName());
    private String idServis;
    private String idTeknisi;


    /**
     * Creates new form DetailService
     */
    public DetailService(
            String idServis,
            String tglMasuk,
        String nama,
        String noHp,
        String alamat,
        String jenis,
        String merek,
        String model,
        String noSeri,
        String keluhan,
        String kelengkapan,
        String status,
        String idTeknisi
) {
    initComponents();
    this.idServis = idServis;
    this.idTeknisi = Session.idUser;

    txtIdService.setText(idServis);
    txtTglMasuk.setText(tglMasuk);
    txtNama.setText(nama);
    txtNohp.setText(noHp);
    txtAlamat.setText(alamat);
    txtJnsBarang.setText(jenis);
    txtMerek.setText(merek);
    txtModel.setText(model);
    txtNoSeri.setText(noSeri);
    txtKeluhan.setText(keluhan);
    txtKelengkapan.setText(kelengkapan);
    tStatus.setSelectedItem(status);
    
     loadPerbaikan(idServis); // 🔥 INI WAJIB

}
    
    private void loadPerbaikan(String idServis) {
    try {
        String sql = "SELECT * FROM perbaikan WHERE id_servis=?";
        Connection conn = Koneksi.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, idServis);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {

            txtKerusakan.setText(rs.getString("kerusakan"));
            txtPerbaikan.setText(rs.getString("tindakan"));
            tBiayaJasa.setText(rs.getString("biaya_jasa"));

//            lblStatus.setText("SUDAH ADA PERBAIKAN");

            loadSparepart(rs.getInt("id_perbaikan"));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
    
    private void loadSparepart(int idPerbaikan) {
    try {
        DefaultTableModel model = (DefaultTableModel) tblGanti.getModel();
        model.setRowCount(0);

        String sql = """
            SELECT b.id_barang, b.nama_barang,
                   ps.qty, ps.harga, ps.subtotal
            FROM perbaikan_sparepart ps
            JOIN barang b ON ps.id_barang = b.id_barang
            WHERE ps.id_perbaikan=?
        """;

        Connection conn = Koneksi.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, idPerbaikan);

        ResultSet rs = ps.executeQuery();

        int no = 1;
        while (rs.next()) {
            model.addRow(new Object[]{
                no++,
                rs.getString("id_barang"),
                rs.getString("nama_barang"),
                rs.getInt("qty"),
                rs.getInt("harga"),
                rs.getInt("subtotal")
            });
        }

        hitungTotal();

    } catch (Exception e) {
//       _toggleError(e);
    }
}


    public void tambahSparepart(
        String idBarang,
        String namaBarang,
        int harga,
        int qty
) {
    DefaultTableModel model = (DefaultTableModel) tblGanti.getModel();

    boolean ditemukan = false;

    for (int i = 0; i < model.getRowCount(); i++) {

        String idTabel = model.getValueAt(i, 1).toString();

        // JIKA BARANG SUDAH ADA
        if (idTabel.equals(idBarang)) {

            int qtyLama = Integer.parseInt(model.getValueAt(i, 3).toString());
            int qtyBaru = qtyLama + qty;

            int subtotalBaru = qtyBaru * harga;

            model.setValueAt(qtyBaru, i, 3);
            model.setValueAt(subtotalBaru, i, 5);

            ditemukan = true;
            break;
        }
    }

    // JIKA BELUM ADA → TAMBAH BARIS BARU
    if (!ditemukan) {

        int no = model.getRowCount() + 1;

        model.addRow(new Object[]{
            no,
            idBarang,
            namaBarang,
            qty,
            harga,
            harga * qty
        });
    }

    hitungTotal();
}

    
    private void hitungTotal() {
    int total = 0;

    for (int i = 0; i < tblGanti.getRowCount(); i++) {
        total += Integer.parseInt(
            tblGanti.getValueAt(i, 4).toString()
        );
    }

    tTotalBrg.setText(String.valueOf(total));
}


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNohp = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTglMasuk = new javax.swing.JTextField();
        txtJnsBarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdService = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMerek = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtNoSeri = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtKelengkapan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtKeluhan = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKerusakan = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPerbaikan = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGanti = new javax.swing.JTable();
        btPilih = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tTotalBrg = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tBiayaJasa = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tStatus = new javax.swing.JComboBox<>();
        btSimpan = new javax.swing.JButton();
        btSelesai = new javax.swing.JButton();
        btKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel1.setText("Detail Service");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nama :");

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("No. HP :");

        txtNohp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtAlamat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Alamat :");

        txtTglMasuk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtJnsBarang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Jenis Barang :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("ID Service :");

        txtIdService.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Tanggal Masuk :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Merek :");

        txtMerek.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Model :");

        txtModel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtNoSeri.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("No. Seri :");

        txtKelengkapan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Kelengkapan :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Keluhan :");

        txtKeluhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Hasil Pengecekan Teknisi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Kerusakan :");

        txtKerusakan.setColumns(20);
        txtKerusakan.setRows(5);
        jScrollPane1.setViewportView(txtKerusakan);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Perbaikan :");

        txtPerbaikan.setColumns(20);
        txtPerbaikan.setRows(5);
        jScrollPane2.setViewportView(txtPerbaikan);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Sparepart Diganti ");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Daftar Sparepart :");

        tblGanti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode Barang", "Nama Barang", "Qty", "Harga", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblGanti);
        if (tblGanti.getColumnModel().getColumnCount() > 0) {
            tblGanti.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        btPilih.setText("PIlih Barang");
        btPilih.addActionListener(this::btPilihActionPerformed);

        jLabel18.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel18.setText("Total Harga Sparepart :");

        tTotalBrg.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        tTotalBrg.setText("00000");

        jLabel20.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel20.setText("Biaya Jasa :");

        tBiayaJasa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel21.setText("Status Service :");

        tStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proses", "Menunggu", "Selesai" }));

        btSimpan.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        btSimpan.setText("Simpan Perbaikan");
        btSimpan.addActionListener(this::btSimpanActionPerformed);

        btSelesai.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        btSelesai.setText("Selesai Service");
        btSelesai.addActionListener(this::btSelesaiActionPerformed);

        btKembali.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        btKembali.setText("Kembali");
        btKembali.addActionListener(this::btKembaliActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel15)
                        .addComponent(jScrollPane2)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btPilih))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tTotalBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBiayaJasa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSelesai)
                        .addGap(18, 18, 18)
                        .addComponent(btKembali)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(btPilih))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(tTotalBrg))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(tBiayaJasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSimpan)
                    .addComponent(btSelesai)
                    .addComponent(btKembali))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdService, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtNama)
                    .addComponent(txtNohp)
                    .addComponent(txtAlamat)
                    .addComponent(txtTglMasuk)
                    .addComponent(txtJnsBarang)
                    .addComponent(txtMerek)
                    .addComponent(txtModel)
                    .addComponent(txtNoSeri)
                    .addComponent(txtKelengkapan)
                    .addComponent(txtKeluhan))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtIdService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTglMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtJnsBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNoSeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtKelengkapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtKeluhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPilihActionPerformed
        // TODO add your handling code here:
        pilihsparepart dialog = new pilihsparepart(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btPilihActionPerformed

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
    Connection conn = null;

    try {
        conn = Koneksi.configDB();
        conn.setAutoCommit(false);

        // ======================
        // INSERT PERBAIKAN
        // ======================
        String sql = "INSERT INTO perbaikan "
                   + "(id_servis, id_teknisi, kerusakan, tindakan, biaya_jasa) "
                   + "VALUES (?,?,?,?,?)";

        PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

        ps.setString(1, idServis);
        ps.setString(2, Session.idUser);
        ps.setString(3, txtKerusakan.getText());
        ps.setString(4, txtPerbaikan.getText());
        ps.setInt(5, Integer.parseInt(tBiayaJasa.getText()));
        ps.executeUpdate();

        ResultSet rs = ps.getGeneratedKeys();
        rs.next();
        int idPerbaikan = rs.getInt(1);

        // ======================
        // INSERT SPAREPART
        // ======================
        for (int i = 0; i < tblGanti.getRowCount(); i++) {

            String idBarang = tblGanti.getValueAt(i, 1).toString();
            int qty = Integer.parseInt(tblGanti.getValueAt(i, 3).toString());
            int harga = Integer.parseInt(tblGanti.getValueAt(i, 4).toString());
            int subtotal = Integer.parseInt(tblGanti.getValueAt(i, 5).toString());

            // insert detail
            String sql2 = "INSERT INTO servis_sparepart "
                        + "(id_servis, id_sparepart, qty, harga, subtotal) "
                        + "VALUES (?,?,?,?,?)";

            PreparedStatement ps2 = conn.prepareStatement(sql2);
            ps2.setInt(1, idPerbaikan);
            ps2.setString(2, idBarang);
            ps2.setInt(3, qty);
            ps2.setInt(4, harga);
            ps2.setInt(5, subtotal);
            ps2.executeUpdate();

            // ======================
            // UPDATE STOK BARANG
            // ======================
            String sqlStok = "UPDATE tbl_barang SET stok = stok - ? WHERE kode_barang=?";
            PreparedStatement psStok = conn.prepareStatement(sqlStok);
            psStok.setInt(1, qty);
            psStok.setString(2, idBarang);
            psStok.executeUpdate();
        }

        // ======================
        // UPDATE STATUS SERVIS
        // ======================
        String sql3 = "UPDATE servis SET status='proses' WHERE id_servis=?";
        PreparedStatement ps3 = conn.prepareStatement(sql3);
        ps3.setString(1, idServis);
        ps3.executeUpdate();

        conn.commit();

        JOptionPane.showMessageDialog(this, "Perbaikan berhasil disimpan");

    } catch (Exception e) {

        if (conn != null) {
            try {
                conn.rollback();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }

        JOptionPane.showMessageDialog(this, "Gagal menyimpan: " + e.getMessage());

    } finally {
        if (conn != null) {
            try {
                conn.setAutoCommit(true);
                conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }


    }//GEN-LAST:event_btSimpanActionPerformed

    private void btKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKembaliActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btKembaliActionPerformed

    private void btSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelesaiActionPerformed
        // TODO add your handling code here:
    try {
        Connection conn = Koneksi.configDB();

        // update tanggal selesai
        String sql1 = "UPDATE perbaikan SET tanggal_selesai = NOW() WHERE id_servis=?";
        PreparedStatement ps1 = conn.prepareStatement(sql1);
        ps1.setString(1, idServis);
        ps1.executeUpdate();

        // update status servis
        String sql2 = "UPDATE servis SET status='selesai' WHERE id_servis=?";
        PreparedStatement ps2 = conn.prepareStatement(sql2);
        ps2.setString(1, idServis);
        ps2.executeUpdate();

        JOptionPane.showMessageDialog(this, "Servis telah selesai");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyelesaikan servis: " + e.getMessage());
    }


    }//GEN-LAST:event_btSelesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DetailService("","","","","","","","","","","","","").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btKembali;
    private javax.swing.JButton btPilih;
    private javax.swing.JButton btSelesai;
    private javax.swing.JButton btSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField tBiayaJasa;
    private javax.swing.JComboBox<String> tStatus;
    private javax.swing.JLabel tTotalBrg;
    private javax.swing.JTable tblGanti;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtIdService;
    private javax.swing.JTextField txtJnsBarang;
    private javax.swing.JTextField txtKelengkapan;
    private javax.swing.JTextField txtKeluhan;
    private javax.swing.JTextArea txtKerusakan;
    private javax.swing.JTextField txtMerek;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoSeri;
    private javax.swing.JTextField txtNohp;
    private javax.swing.JTextArea txtPerbaikan;
    private javax.swing.JTextField txtTglMasuk;
    // End of variables declaration//GEN-END:variables
}
