/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mscompapp;

import config.Koneksi;
import java.awt.GraphicsEnvironment;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    public static String namaUser;
    
    public static String role;
    public static String idUser;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.namaUser = Session.namaUser;
        this.role = Session.level;
        this.idUser = Session.idUser;
        this.getRootPane().setDefaultButton(btLogin);
        
        // 1. Ambil ukuran layar yang tersedia (sudah dipotong Taskbar)
    GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
    this.setMaximizedBounds(env.getMaximumWindowBounds());
    
    // 2. Set state ke maximized
    this.setExtendedState(this.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
    
    this.setResizable(true); 

// Memaksa window untuk langsung dalam kondisi Maximized saat dibuka
this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tPass = new javax.swing.JPasswordField();
        tUsn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 120, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Username :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 295, 150, 60));

        btLogin.setBackground(new java.awt.Color(153, 255, 153));
        btLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btLogin.setText("LOGIN");
        btLogin.setFocusPainted(false);
        btLogin.addActionListener(this::btLoginActionPerformed);
        jPanel1.add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, 200, 60));

        jLabel1.setFont(new java.awt.Font("Swis721 Hv BT", 1, 35)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 150, 60));

        tPass.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tPass.addActionListener(this::tPassActionPerformed);
        jPanel1.add(tPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 340, 50));

        tUsn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tUsn.addActionListener(this::tUsnActionPerformed);
        jPanel1.add(tUsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 340, 50));

        jLabel4.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 25)); // NOI18N
        jLabel4.setText("username dan password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 340, 40));

        jLabel6.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 25)); // NOI18N
        jLabel6.setText("Silahkan masukkan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 270, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 1030));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backlogin.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 1310, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here
        try {
            String sql = "SELECT * FROM tbl_user WHERE username='" + tUsn.getText() 
                       + "' AND password='" + new String(tPass.getPassword()) + "'";
            java.sql.Connection conn = (java.sql.Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            if (res.next()) {
                // 1. Ambil data
                String id = res.getString("id_user");
                String nama = res.getString("nama");
                String hakAkses = res.getString("role");

                // 2. ISI SESSION (Wajib agar Teknisi.java tidak crash)
                Session.idUser = id;
                Session.namaUser = nama;
                Session.level = hakAkses; 

                // 3. Gunakan Try-Catch khusus saat membuka Dashboard
                try {
                    Dashboard dash = new Dashboard(nama, hakAkses); 

                    // Pastikan objek dash berhasil dibuat sebelum mengatur lokasi
                    if (dash != null) {
                        dash.setLocationRelativeTo(null);
                        dash.setVisible(true);
                        this.dispose();
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Gagal memuat Dashboard: " + ex.getMessage());
                    ex.printStackTrace(); 
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Username atau Password Salah");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error Login: " + e.getMessage());
        }
    }//GEN-LAST:event_btLoginActionPerformed

    private void tPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPassActionPerformed
        // TODO add your handling code here:
        btLogin.doClick();
    }//GEN-LAST:event_tPassActionPerformed

    private void tUsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsnActionPerformed
        // TODO add your handling code here:
        tPass.requestFocus();
    }//GEN-LAST:event_tUsnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tPass;
    private javax.swing.JTextField tUsn;
    // End of variables declaration//GEN-END:variables
}
