/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mscompapp;

import java.awt.BorderLayout;
import java.text.DecimalFormat;

/**
 *
 * @author Acer Aspire Lite 15
 */
public class PKelLaporan extends javax.swing.JPanel {

    /**
     * Creates new form PKelLaporan
     */
    public PKelLaporan() {
        initComponents();
        
        jPanel4.setLayout(new java.awt.BorderLayout());
    
    // Listener untuk perpindahan combo box
    jComboBox1.addActionListener(e -> gantiHalamanLaporan());
    
    // KUNCI PERBAIKAN: Gunakan invokeLater agar laporan muncul 
    // SETELAH sistem tahu ukuran pasti dari jPanel4
    java.awt.EventQueue.invokeLater(() -> {
        // Pastikan combobox terpilih ke Laporan Bulanan
        jComboBox1.setSelectedItem("Laporan bulanan");
        gantiHalamanLaporan();
    });
    }
    
    
    public void setInfoPendapatan(String labelJudul, int totalUang) {
    // Gunakan invokeLater agar berjalan di urutan terakhir antrean UI
    java.awt.EventQueue.invokeLater(() -> {
        if (jLabel3 != null && txtTotalPendapatan != null) {
            jLabel3.setText(labelJudul);
            
            DecimalFormat df = new DecimalFormat("#,###");
            txtTotalPendapatan.setText("Rp " + df.format(totalUang));
            
            txtTotalPendapatan.revalidate();
            txtTotalPendapatan.repaint();
        } else {
            // Jika masih belum siap, coba lagi dalam 500ms (Opsional)
            System.out.println("Sistem menunggu label siap...");
        }
    });
}
    
    
    
    // Method Public untuk menghitung pendapatan (Dipanggil oleh Panel Anak)
    private void gantiHalamanLaporan() {
        try {
            jPanel4.removeAll();
jPanel4.setLayout(new java.awt.BorderLayout()); // Pastikan ini BorderLayout            
            Object selectedItem = jComboBox1.getSelectedItem();
            String pilihan = (selectedItem != null) ? selectedItem.toString() : "";
            
            if (pilihan.equalsIgnoreCase("Laporan harian")) {
                jPanel4.add(new LapHarian(this), BorderLayout.CENTER);
            } else if (pilihan.equalsIgnoreCase("Laporan mingguan")) {
                jPanel4.add(new LapMingguan(this), BorderLayout.CENTER);
            } else if (pilihan.equalsIgnoreCase("Laporan bulanan")) {
                jPanel4.add(new LapBulanan(this), BorderLayout.CENTER);
            }
            
            jPanel4.revalidate();
            jPanel4.repaint();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    // Gunakan BorderLayout pada panel utama agar bisa memenuhi layar secara dinamis
    this.setLayout(new java.awt.BorderLayout(10, 10));
    this.setBackground(new java.awt.Color(230, 233, 237)); // Warna background abu-abu soft khas dashboard

    // =========================================================================
    // HEADER & FILTER (ATAS)
    // =========================================================================
    jPanel1 = new javax.swing.JPanel();
    jPanel1.setBackground(java.awt.Color.WHITE);
    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLACK));
    jPanel1.setLayout(new java.awt.BorderLayout());

    // JUDUL LAPORAN
    jLabel1 = new javax.swing.JLabel();
    jLabel1.setBackground(new java.awt.Color(4, 102, 200));
    jLabel1.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14));
    jLabel1.setForeground(java.awt.Color.WHITE);
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("LAPORAN DATA SERVICE");
    jLabel1.setOpaque(true);
    jLabel1.setPreferredSize(new java.awt.Dimension(0, 40));
    jPanel1.add(jLabel1, java.awt.BorderLayout.NORTH);

    // PANEL FILTER (Cari & Total Pendapatan)
    javax.swing.JPanel pnlFilter = new javax.swing.JPanel(new java.awt.GridBagLayout());
    pnlFilter.setOpaque(false);
    java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
    
    // Elemen Filter (Kiri)
    gbc.insets = new java.awt.Insets(10, 15, 10, 5);
    gbc.gridx = 0; gbc.gridy = 0;
    pnlFilter.add(new javax.swing.JLabel("Filter :"), gbc);

    jComboBox1 = new javax.swing.JComboBox<>();
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laporan Bulanan", "Laporan Mingguan", "Laporan Harian" }));
    jComboBox1.setPreferredSize(new java.awt.Dimension(200, 30));
    gbc.gridx = 1;
    pnlFilter.add(jComboBox1, gbc);

    // Spacer Tengah (Agar Total Pendapatan terdorong ke kanan)
    gbc.gridx = 2; gbc.weightx = 1.0;
    pnlFilter.add(new javax.swing.Box.Filler(new java.awt.Dimension(0,0), new java.awt.Dimension(0,0), new java.awt.Dimension(32767,0)), gbc);

    // Total Pendapatan (Kanan)
    gbc.weightx = 0;
    gbc.gridx = 3;
    jLabel3 = new javax.swing.JLabel("Total Pendapatan :");
pnlFilter.add(jLabel3, gbc);

    txtTotalPendapatan = new javax.swing.JLabel();
    txtTotalPendapatan.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13));
    txtTotalPendapatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallet.png"))); 
    txtTotalPendapatan.setText("Rp 0,00");
    gbc.gridx = 4;
    gbc.insets = new java.awt.Insets(10, 5, 10, 15);
    pnlFilter.add(txtTotalPendapatan, gbc);

    jPanel1.add(pnlFilter, java.awt.BorderLayout.CENTER);
    
    // Tambahkan Panel Atas ke posisi NORTH
    this.add(jPanel1, java.awt.BorderLayout.NORTH);

    // =========================================================================
    // AREA TABEL LAPORAN (TENGAH)
    // =========================================================================
    jPanel4 = new javax.swing.JPanel();
    jPanel4.setBackground(java.awt.Color.WHITE);
    jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLACK));
    jPanel4.setLayout(new java.awt.BorderLayout());

    // NOTE: Tambahkan JScrollPane dan JTable Anda ke sini nanti
    // Contoh penggunaan:
    // jScrollPaneLaporan.setViewportView(tblLaporan);
    // jPanel4.add(jScrollPaneLaporan, java.awt.BorderLayout.CENTER);

    // Tambahkan Panel Tabel ke posisi CENTER (Auto Expand)
    this.add(jPanel4, java.awt.BorderLayout.CENTER);
    
    // Margin padding luar agar tidak nempel ke pinggir layar monitor
    this.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
}// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel txtTotalPendapatan;
    // End of variables declaration//GEN-END:variables
}
