/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mscompapp;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
/**
 *
 * @author ASUS
 */
public class sidebar_admin extends javax.swing.JPanel {

    /**
     * Creates new form sidebar_admin
     */
    private Dashboard dashboard;
    
    public sidebar_admin(Dashboard dashboard) {
        this.dashboard = dashboard;
        initComponents();
        
        JLabel[] menuLabels = {
            menu,
            kelolaservice,
            lapservice,
            keluser,
            lblKelolaBarang,
            kelkatperangkat,
            lblKelkatbarang,
            lblKelStock,
            keluser,
            lblKelPlgn,
            pengaturan
        };
        
        setHoverEffect(menuLabels);
    }
    
    public void setHoverEffect(JLabel[] daftarLabel) {
    
    // Loop untuk setiap label yang ada di daftar
    for (JLabel label : daftarLabel) {
        
        // 1. Pastikan label bisa berubah warna (Opaque harus true)
        label.setOpaque(true);
        
        // 2. Tambahkan pendengar (Listener) mouse
        label.addMouseListener(new MouseAdapter() {
            
            @Override
            public void mouseEntered(MouseEvent e) {
                // Saat mouse masuk: Ubah jadi Abu-abu & Ganti kursor jadi tangan
                Component c = e.getComponent(); // Mengambil komponen yang disentuh
                c.setBackground(new Color(4, 102, 200)); 
                c.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                // Saat mouse keluar: Kembalikan jadi Putih (atau warna asal)
                Component c = e.getComponent();
                c.setBackground(new Color(0, 18, 51));
            }
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelkatperangkat = new javax.swing.JLabel();
        lblKelPlgn = new javax.swing.JLabel();
        kelolaservice = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        keluser = new javax.swing.JLabel();
        lblKelolaBarang = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lapservice = new javax.swing.JLabel();
        lblKelkatbarang = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblKelStock = new javax.swing.JLabel();
        pengaturan = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 18, 51));
        setForeground(new java.awt.Color(51, 65, 92));
        setMaximumSize(new java.awt.Dimension(200, 980));
        setMinimumSize(new java.awt.Dimension(200, 980));
        setPreferredSize(new java.awt.Dimension(200, 980));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kelkatperangkat.setBackground(new java.awt.Color(0, 18, 51));
        kelkatperangkat.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        kelkatperangkat.setForeground(new java.awt.Color(255, 255, 255));
        kelkatperangkat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jenisperangkat.png"))); // NOI18N
        kelkatperangkat.setText("Jenis perangkat");
        kelkatperangkat.setOpaque(true);
        kelkatperangkat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kelkatperangkatMouseClicked(evt);
            }
        });
        add(kelkatperangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 210, 43));

        lblKelPlgn.setBackground(new java.awt.Color(0, 18, 51));
        lblKelPlgn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        lblKelPlgn.setForeground(new java.awt.Color(255, 255, 255));
        lblKelPlgn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-customer-32.png"))); // NOI18N
        lblKelPlgn.setText("Kelola Pelanggan");
        lblKelPlgn.setOpaque(true);
        lblKelPlgn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKelPlgnMouseClicked(evt);
            }
        });
        add(lblKelPlgn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 210, 43));

        kelolaservice.setBackground(new java.awt.Color(0, 18, 51));
        kelolaservice.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        kelolaservice.setForeground(new java.awt.Color(255, 255, 255));
        kelolaservice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kelservice.png"))); // NOI18N
        kelolaservice.setText("Kelola Service");
        kelolaservice.setOpaque(true);
        kelolaservice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kelolaserviceMouseClicked(evt);
            }
        });
        add(kelolaservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, 43));

        menu.setBackground(new java.awt.Color(0, 18, 51));
        menu.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu (1).png"))); // NOI18N
        menu.setText("Menu");
        menu.setOpaque(true);
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 225, 43));

        keluser.setBackground(new java.awt.Color(0, 18, 51));
        keluser.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        keluser.setForeground(new java.awt.Color(255, 255, 255));
        keluser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keluser.png"))); // NOI18N
        keluser.setText("Kelola User");
        keluser.setOpaque(true);
        keluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluserMouseClicked(evt);
            }
        });
        add(keluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 210, 43));

        lblKelolaBarang.setBackground(new java.awt.Color(0, 18, 51));
        lblKelolaBarang.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        lblKelolaBarang.setForeground(new java.awt.Color(255, 255, 255));
        lblKelolaBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kelbarang.png"))); // NOI18N
        lblKelolaBarang.setText("Kelola Barang");
        lblKelolaBarang.setOpaque(true);
        lblKelolaBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKelolaBarangMouseClicked(evt);
            }
        });
        add(lblKelolaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 210, 43));

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOG OUT");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 180, 50));

        lapservice.setBackground(new java.awt.Color(0, 18, 51));
        lapservice.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        lapservice.setForeground(new java.awt.Color(255, 255, 255));
        lapservice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/laporan.png"))); // NOI18N
        lapservice.setText("Laporan Service");
        lapservice.setOpaque(true);
        lapservice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lapserviceMouseClicked(evt);
            }
        });
        add(lapservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, 43));

        lblKelkatbarang.setBackground(new java.awt.Color(0, 18, 51));
        lblKelkatbarang.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        lblKelkatbarang.setForeground(new java.awt.Color(255, 255, 255));
        lblKelkatbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kategoribarang.png"))); // NOI18N
        lblKelkatbarang.setText("Kategori barang");
        lblKelkatbarang.setOpaque(true);
        lblKelkatbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKelkatbarangMouseClicked(evt);
            }
        });
        add(lblKelkatbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 210, 43));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("_____________________________________________");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 215, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("_____________________________________________");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 74, -1, -1));

        lblKelStock.setBackground(new java.awt.Color(0, 18, 51));
        lblKelStock.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        lblKelStock.setForeground(new java.awt.Color(255, 255, 255));
        lblKelStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stok.png"))); // NOI18N
        lblKelStock.setText("Kelola Stock");
        lblKelStock.setOpaque(true);
        lblKelStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKelStockMouseClicked(evt);
            }
        });
        add(lblKelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 210, 43));

        pengaturan.setBackground(new java.awt.Color(0, 18, 51));
        pengaturan.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        pengaturan.setForeground(new java.awt.Color(255, 255, 255));
        pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/setting (1).png"))); // NOI18N
        pengaturan.setText("Pengaturan");
        pengaturan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengaturanMouseClicked(evt);
            }
        });
        add(pengaturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 536, 210, 43));
    }// </editor-fold>//GEN-END:initComponents

    private void kelkatperangkatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelkatperangkatMouseClicked
        // TODO add your handling code here:
        dashboard.switchPanel(new PKatService());
        dashboard.setPanelIndex(5);
        
    }//GEN-LAST:event_kelkatperangkatMouseClicked
  
    private void lblKelPlgnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKelPlgnMouseClicked
        // TODO add your handling code here:
        dashboard.switchPanel(new PKelPelanggan());
        dashboard.setPanelIndex(8);
    }//GEN-LAST:event_lblKelPlgnMouseClicked

    private void kelolaserviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelolaserviceMouseClicked
        // TODO add your handling code here:
        dashboard.switchPanel(new PKelService());
        dashboard.setPanelIndex(1);
    }//GEN-LAST:event_kelolaserviceMouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:
        dashboard.switchPanel(new Beranda());
        dashboard.setPanelIndex(0);
    }//GEN-LAST:event_menuMouseClicked

    private void keluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluserMouseClicked
        // TODO add your handling code here:
        dashboard.switchPanel(new PKelUser());
        dashboard.setPanelIndex(3);
    }//GEN-LAST:event_keluserMouseClicked

    private void lblKelolaBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKelolaBarangMouseClicked
        // TODO add your handling code here:
        dashboard.switchPanel(new PKelBarang());
        dashboard.setPanelIndex(4);
    }//GEN-LAST:event_lblKelolaBarangMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        dashboard.logout();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void lapserviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lapserviceMouseClicked
        // TODO add your handling code here:
                dashboard.switchPanel(new PKelLaporan());
                dashboard.setPanelIndex(2);

    }//GEN-LAST:event_lapserviceMouseClicked

    private void lblKelkatbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKelkatbarangMouseClicked
        // TODO add your handling code here:
        dashboard.switchPanel(new PKatBarang());
        dashboard.setPanelIndex(6);
    }//GEN-LAST:event_lblKelkatbarangMouseClicked

    private void lblKelStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKelStockMouseClicked
        // TODO add your handling code here:
        dashboard.switchPanel(new PKelStok());
        dashboard.setPanelIndex(7);
    }//GEN-LAST:event_lblKelStockMouseClicked

    private void pengaturanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengaturanMouseClicked
        // TODO add your handling code here:
        dashboard.switchPanel(new Pengaturan());
        dashboard.setPanelIndex(9);
    }//GEN-LAST:event_pengaturanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel kelkatperangkat;
    private javax.swing.JLabel kelolaservice;
    private javax.swing.JLabel keluser;
    private javax.swing.JLabel lapservice;
    private javax.swing.JLabel lblKelPlgn;
    private javax.swing.JLabel lblKelStock;
    private javax.swing.JLabel lblKelkatbarang;
    private javax.swing.JLabel lblKelolaBarang;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel pengaturan;
    // End of variables declaration//GEN-END:variables
}
