/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.Timer;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane; // [BARU] Untuk menampilkan pesan konfirmasi
import login.Login;
/**
 *
 * @author ASUS
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());
    public String namaUser;
    
    /**
     * Creates new form Dashboard
     */
    public Dashboard(String username) {
        initComponents();
        this.namaUser = username;
        lblWelcome.setText("Selamat Datang, " + username);
        
        switchPanel(new beranda(this));
        
        Timer timer = new Timer(1000, new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        // Format tanggal dan waktu
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMMM yyyy HH:mm:ss");
        String waktuSekarang = sdf.format(new Date());
        lblTanggal.setText(waktuSekarang);
    }
});
timer.start();

btnLogout.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnLogoutActionPerformed(e);
            }
        });
    }
    
    private void switchPanel(javax.swing.JPanel panel) {
        pMain.removeAll();
        pMain.add(panel);
        pMain.repaint();
        pMain.revalidate();
    }
    
    // [BARU] Method Public agar bisa dipanggil oleh 'beranda.java'
    public void bukaMenuKelolaUser() {
        switchPanel(new PKelUser());
    }
    
    // [BARU] Method Public agar bisa dipanggil untuk balik ke beranda (opsional)
    public void bukaMenuBeranda() {
        switchPanel(new beranda(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNav = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pSide = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblKelolaUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pNav.setBackground(new java.awt.Color(102, 102, 255));
        pNav.setMinimumSize(new java.awt.Dimension(1920, 140));
        pNav.setPreferredSize(new java.awt.Dimension(1920, 140));
        pNav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblWelcome.setText("Welcome");
        pNav.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 10, 350, 40));

        lblTanggal.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        lblTanggal.setText("Tanggal");
        pNav.add(lblTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 50, 350, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo toko.png"))); // NOI18N
        pNav.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 421, 100));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("=");
        pNav.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 60));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        pNav.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 30, 150, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("=");
        pNav.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        getContentPane().add(pNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        pSide.setBackground(new java.awt.Color(204, 204, 204));
        pSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        jLabel1.setText("Menu");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pSide.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 50));

        lblKelolaUser.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        lblKelolaUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKelolaUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        lblKelolaUser.setText("Kelola User");
        lblKelolaUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKelolaUserMouseClicked(evt);
            }
        });
        pSide.add(lblKelolaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("daftar");
        jLabel3.setToolTipText("");
        pSide.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 50));

        getContentPane().add(pSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 980));

        pMain.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 1700, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblKelolaUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKelolaUserMouseClicked
        // TODO add your handling code here:
        switchPanel(new PKelUser());
    }//GEN-LAST:event_lblKelolaUserMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        switchPanel(new beranda(this));
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int jawaban = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin Logout?", 
                "Konfirmasi Keluar", 
                JOptionPane.YES_NO_OPTION);
        
        if (jawaban == JOptionPane.YES_OPTION) {
            // 2. Tutup Dashboard saat ini
            this.dispose();
            
            // 3. Buka kembali halaman Login
            Login loginPage = new Login();
            loginPage.setVisible(true);
            loginPage.setLocationRelativeTo(null); // Biar muncul di tengah layar
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblKelolaUser;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pNav;
    private javax.swing.JPanel pSide;
    // End of variables declaration//GEN-END:variables
}
