/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin;
import config.Koneksi;
import java.sql.Connection;        // Untuk koneksi ke database
import java.sql.PreparedStatement; // Untuk menjalankan query SQL yang aman
import java.sql.ResultSet;         // Untuk menampung hasil data dari database
import java.sql.Statement;         // Untuk mengirim perintah SQL dasar
import javax.swing.JOptionPane;    // Untuk memunculkan pesan dialog (Pop-up)
import javax.swing.table.DefaultTableModel; // Untuk mengatur data pada JTable

/**
 *
 * @author ASUS
 */
public class PKelUser extends javax.swing.JPanel {
    private boolean isEditMode = false;
    /**
     * Creates new form pDashboard
     */
    public PKelUser() {
        initComponents();
        load_table();
        auto_number();
    }
    
    private void load_table() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No"); model.addColumn("Username"); 
    model.addColumn("Password"); model.addColumn("Nama"); model.addColumn("Role");
    try {
        String sql = "SELECT * FROM tbl_user";
        java.sql.Connection conn = (java.sql.Connection)Koneksi.configDB();
        java.sql.ResultSet res = conn.createStatement().executeQuery(sql);
        while(res.next()){
            model.addRow(new Object[]{res.getString(1), res.getString(2), 
                res.getString(3), res.getString(4), res.getString(5)});
        }
        jTable1.setModel(model);
    } catch (Exception e) { System.out.println(e.getMessage()); }
}

// Mengambil calon nomor ID selanjutnya secara otomatis
private void auto_number() {
    try {
        java.sql.Connection conn = (java.sql.Connection)Koneksi.configDB();
        java.sql.ResultSet res = conn.createStatement().executeQuery("SELECT MAX(id_user) FROM tbl_user");
        if (res.next()) {
            txtNo.setText(String.valueOf(res.getInt(1) + 1));
        } else {
            txtNo.setText("1");
        }
    } catch (Exception e) { txtNo.setText("1"); }
}

// Membersihkan form dan meriset ke mode "Tambah"
private void bersihkanForm() {
    txtUsn.setText("");
    txtPass.setText("");
    txtNama.setText("");
    cbRole.setSelectedIndex(0);
    txtCari.setText(""); // Bersihkan kolom cari juga
    isEditMode = false;   // Kembali ke mode Tambah
    auto_number();        // Beri nomor ID baru otomatis
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbRole = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jRadioButton1.setText("jRadioButton1");

        setMaximumSize(new java.awt.Dimension(1060, 620));
        setMinimumSize(new java.awt.Dimension(1700, 960));
        setPreferredSize(new java.awt.Dimension(1700, 960));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel2.setText("Username :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 210, -1));

        txtUsn.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtUsn.addActionListener(this::txtUsnActionPerformed);
        jPanel1.add(txtUsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 269, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 210, -1));

        txtPass.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 269, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nama :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 180, -1));

        txtNama.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtNama.addActionListener(this::txtNamaActionPerformed);
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 269, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel5.setText("Role :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 170, -1));

        cbRole.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "teknisi" }));
        jPanel1.add(cbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 269, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel6.setText("No :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, -1));

        txtNo.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtNo.addActionListener(this::txtNoActionPerformed);
        jPanel1.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 269, -1));

        btnSimpan.setBackground(new java.awt.Color(153, 153, 153));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 269, 55));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("TAMBAH USER");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(72, 72, 72))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 948));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Username", "Password", "Nama", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1335, 640));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("DAFTAR USER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(262, 262, 262))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1347, -1));
        jPanel2.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 353, 40));

        btnEdit.setBackground(new java.awt.Color(204, 204, 204));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        jPanel2.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, 40));

        btnRefresh.setBackground(new java.awt.Color(51, 255, 51));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);
        jPanel2.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 39));

        btnCari.setBackground(new java.awt.Color(51, 255, 51));
        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCari.setText("CARI");
        btnCari.addActionListener(this::btnCariActionPerformed);
        jPanel2.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, 42));

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        jPanel2.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, 40));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsnActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
        java.sql.Connection conn = (java.sql.Connection)Koneksi.configDB();
        String sql;

        if (isEditMode == false) {
            // JALANKAN TAMBAH USER (ID diabaikan karena Auto Increment)
            sql = "INSERT INTO tbl_user (username, password, nama, role) VALUES (?,?,?,?)";
        } else {
            // JALANKAN UBAH USER
            sql = "UPDATE tbl_user SET username=?, password=?, nama=?, role=? WHERE id_user=?";
        }

        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txtUsn.getText());
        pst.setString(2, txtPass.getText());
        pst.setString(3, txtNama.getText());
        pst.setString(4, cbRole.getSelectedItem().toString());
        
        if (isEditMode) {
            pst.setString(5, txtNo.getText());
        }

        pst.execute();
        javax.swing.JOptionPane.showMessageDialog(null, "Berhasil!");
        load_table();
        bersihkanForm(); // Otomatis balik ke mode tambah & No baru
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        load_table();
    bersihkanForm();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No"); model.addColumn("Username"); 
    model.addColumn("Password"); model.addColumn("Nama"); model.addColumn("Role");
    try {
        // Mencari berdasarkan Username atau Nama
        String sql = "SELECT * FROM tbl_user WHERE username LIKE '%" + txtCari.getText() 
                     + "%' OR nama LIKE '%" + txtCari.getText() + "%'";
        java.sql.Connection conn = (java.sql.Connection)Koneksi.configDB();
        java.sql.ResultSet res = conn.createStatement().executeQuery(sql);
        while(res.next()){
            model.addRow(new Object[]{res.getString(1), res.getString(2), 
                res.getString(3), res.getString(4), res.getString(5)});
        }
        jTable1.setModel(model);
    } catch (Exception e) { 
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage()); 
    }
    }//GEN-LAST:event_btnCariActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int barisTerpilih = jTable1.getSelectedRow();

    // 2. Cek apakah ada baris yang diklik/dipilih
    if (barisTerpilih == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih dulu baris di tabel yang ingin diedit!");
    } else {
        // 3. Ambil ID dan Nama untuk konfirmasi
        String id = jTable1.getValueAt(barisTerpilih, 0).toString();
        String nama = jTable1.getValueAt(barisTerpilih, 3).toString();

        // 4. Munculkan Pop-up Konfirmasi
        int konfirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Apakah Anda ingin mengedit data " + nama + " (ID: " + id + ")?", 
                "Konfirmasi Edit", javax.swing.JOptionPane.YES_NO_OPTION);

        if (konfirm == javax.swing.JOptionPane.YES_OPTION) {
            // 5. Pindahkan data dari tabel ke form sebelah kiri
            txtNo.setText(id);
            txtUsn.setText(jTable1.getValueAt(barisTerpilih, 1).toString());
            txtPass.setText(jTable1.getValueAt(barisTerpilih, 2).toString());
            txtNama.setText(nama);
            cbRole.setSelectedItem(jTable1.getValueAt(barisTerpilih, 4).toString());

            // 6. Ubah saklar isEditMode menjadi true
            isEditMode = true;
            
            // Beri notifikasi kecil agar admin tahu form sudah siap diubah
            javax.swing.JOptionPane.showMessageDialog(this, "Data sudah dipindahkan ke form. Silakan ubah lalu klik Simpan.");
        }
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here :
        int barisTerpilih = jTable1.getSelectedRow();

    // 2. Cek apakah ada baris yang dipilih
    if (barisTerpilih == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Klik dulu baris pada tabel yang ingin dihapus!");
    } else {
        // 3. Ambil ID dari kolom pertama (index 0) pada baris yang dipilih
        String idHapus = jTable1.getValueAt(barisTerpilih, 0).toString();
        String namaHapus = jTable1.getValueAt(barisTerpilih, 3).toString(); // Ambil kolom Nama untuk konfirmasi

        // 4. Konfirmasi penghapusan
        int konfirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Yakin ingin menghapus User: " + namaHapus + " (ID: " + idHapus + ")?", 
                "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);

        if (konfirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                java.sql.Connection conn = (java.sql.Connection)Koneksi.configDB();
                String sql = "DELETE FROM tbl_user WHERE id_user = '" + idHapus + "'";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();

                javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                
                // 5. Refresh data
                load_table();
                bersihkanForm(); // Agar Auto Number di form kiri juga terupdate
                
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal Menghapus: " + e.getMessage());
            }
        }
    }
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNo;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsn;
    // End of variables declaration//GEN-END:variables
}
